title:       XAI^3 Workshop at ECAI 2023
description: Joint workshops on XAI methods, challenges and applications at ECAI 2023

timezone: Europe/Warsaw

navigation:
  Home: "/"
  Call for Papers: "/cfp"
  Schedule: "/schedule"
  # Accepted Papers: "/papers"
  Related Workshops: "/related_workshops"

markdown: kramdown

kramdown:
  parse_span_html: true
  parse_block_html: true

plugins:
  - jekyll-seo-tag
  - jekyll-spaceship
  
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
