title:       XAI^3 Workshop at ECAI 2023
description: Joint workshops on XAI methods, challenges and applications at the 26th European Conference on Artificial Intelligence

timezone: Europe/Warsaw

navigation:
  Home: "/"
  Call for Papers: "/cfp"
  # Accepted Papers: "/papers"
  ⭐ Invited Speakers ⭐: "/speakers"
  Organisers: "/organisers"
  Schedule: "/schedule"
  Main Conference: https://ecai2023.eu

markdown: kramdown

kramdown:
  parse_span_html: true
  parse_block_html: true

plugins:
  - jekyll-seo-tag
  - jekyll-spaceship

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
